[package]
name = "rdbc-postgres"
description = " Postgres RDBC Driver"
version = "0.2.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"

edition = "2018"

[dependencies]
rdbc = { path = "../rdbc", version = "0.2.0" }

postgres = "0.19.5"
sqlparser = "0.35.0"
