name: Rust CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build

    - name: Start database servers
      run: docker-compose up -d
    - name: Run tests
      run: cargo test
